name: Liquibase CI/CD for PostgreSQL

on:
  push:
    paths:
      - 'changelog/**'
      - '.github/workflows/**'
      - '.secrets'

jobs:
  liquibase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Liquibase
        run: |
          curl -sL https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.zip -o liquibase.zip
          unzip -o liquibase.zip -d /usr/local/bin/liquibase
          chmod +x /usr/local/bin/liquibase/liquibase
          echo "/usr/local/bin/liquibase" >> $GITHUB_PATH
      - name: Debug Secrets
        run: |
          echo "URL: jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          echo "USER: ${{ secrets.DB_USER }}"

      - name: Run Liquibase Migrations
        run: |
          /usr/local/bin/liquibase/liquibase \
            --changeLogFile=changelog/db.changelog-master.yaml \
            --url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASS }} \
            update
